MAJOR_VERSION  = 0
MINOR_VERSION  = 0
RELEASE_NUMBER = 1
SUFFIX         = "b1"
VERSION_STRING = "{}.{}.{}{}".format(MAJOR_VERSION, MINOR_VERSION, RELEASE_NUMBER, SUFFIX)

VERSION = (MAJOR_VERSION, MINOR_VERSION, RELEASE_NUMBER, SUFFIX)
